name: natura
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  provider: ^6.0.0
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/fondos/
    - assets/iconos/
    - assets/img/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNowDisplay-Black.ttf
        - asset: assets/fonts/HelveticaNowDisplay-BlackIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Bold.ttf
        - asset: assets/fonts/HelveticaNowDisplay-BoldIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-ExtBdIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-ExtBlk.ttf
        - asset: assets/fonts/HelveticaNowDisplay-ExtBlkIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-ExtLt.ttf
        - asset: assets/fonts/HelveticaNowDisplay-ExtLtIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-ExtraBold.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Hairline.ttf
        - asset: assets/fonts/HelveticaNowDisplay-HairlineI.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Light.ttf
        - asset: assets/fonts/HelveticaNowDisplay-LightIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-MedIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Medium.ttf
        - asset: assets/fonts/HelveticaNowDisplay-RegIta.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Regular.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Thin.ttf
        - asset: assets/fonts/HelveticaNowDisplay-ThinIta.ttf

